/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables;


import br.edu.uni7.sicamovie.persistence.BdSicaMovie;
import br.edu.uni7.sicamovie.persistence.Indexes;
import br.edu.uni7.sicamovie.persistence.Keys;
import br.edu.uni7.sicamovie.persistence.tables.records.FuncionarioHorarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FuncionarioHorario extends TableImpl<FuncionarioHorarioRecord> {

    private static final long serialVersionUID = 1685127584;

    /**
     * The reference instance of <code>bd_sica_movie.funcionario_horario</code>
     */
    public static final FuncionarioHorario FUNCIONARIO_HORARIO = new FuncionarioHorario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FuncionarioHorarioRecord> getRecordType() {
        return FuncionarioHorarioRecord.class;
    }

    /**
     * The column <code>bd_sica_movie.funcionario_horario.funcionario_id</code>.
     */
    public final TableField<FuncionarioHorarioRecord, Integer> FUNCIONARIO_ID = createField(DSL.name("funcionario_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bd_sica_movie.funcionario_horario.horario_id</code>.
     */
    public final TableField<FuncionarioHorarioRecord, Integer> HORARIO_ID = createField(DSL.name("horario_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>bd_sica_movie.funcionario_horario</code> table reference
     */
    public FuncionarioHorario() {
        this(DSL.name("funcionario_horario"), null);
    }

    /**
     * Create an aliased <code>bd_sica_movie.funcionario_horario</code> table reference
     */
    public FuncionarioHorario(String alias) {
        this(DSL.name(alias), FUNCIONARIO_HORARIO);
    }

    /**
     * Create an aliased <code>bd_sica_movie.funcionario_horario</code> table reference
     */
    public FuncionarioHorario(Name alias) {
        this(alias, FUNCIONARIO_HORARIO);
    }

    private FuncionarioHorario(Name alias, Table<FuncionarioHorarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private FuncionarioHorario(Name alias, Table<FuncionarioHorarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FuncionarioHorario(Table<O> child, ForeignKey<O, FuncionarioHorarioRecord> key) {
        super(child, key, FUNCIONARIO_HORARIO);
    }

    @Override
    public Schema getSchema() {
        return BdSicaMovie.BD_SICA_MOVIE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FUNCIONARIO_HORARIO_FK_FILMEHORARIO_HORARIO_ID, Indexes.FUNCIONARIO_HORARIO_PRIMARY);
    }

    @Override
    public UniqueKey<FuncionarioHorarioRecord> getPrimaryKey() {
        return Keys.KEY_FUNCIONARIO_HORARIO_PRIMARY;
    }

    @Override
    public List<UniqueKey<FuncionarioHorarioRecord>> getKeys() {
        return Arrays.<UniqueKey<FuncionarioHorarioRecord>>asList(Keys.KEY_FUNCIONARIO_HORARIO_PRIMARY);
    }

    @Override
    public List<ForeignKey<FuncionarioHorarioRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FuncionarioHorarioRecord, ?>>asList(Keys.FK_FUNCIONARIOHORARIO_FUNCIONARIO_ID, Keys.FK_FILMEHORARIO_HORARIO_ID);
    }

    public Funcionario funcionario() {
        return new Funcionario(this, Keys.FK_FUNCIONARIOHORARIO_FUNCIONARIO_ID);
    }

    public Horario horario() {
        return new Horario(this, Keys.FK_FILMEHORARIO_HORARIO_ID);
    }

    @Override
    public FuncionarioHorario as(String alias) {
        return new FuncionarioHorario(DSL.name(alias), this);
    }

    @Override
    public FuncionarioHorario as(Name alias) {
        return new FuncionarioHorario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FuncionarioHorario rename(String name) {
        return new FuncionarioHorario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FuncionarioHorario rename(Name name) {
        return new FuncionarioHorario(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
