/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables;


import br.edu.uni7.sicamovie.persistence.BdSicaMovie;
import br.edu.uni7.sicamovie.persistence.Indexes;
import br.edu.uni7.sicamovie.persistence.Keys;
import br.edu.uni7.sicamovie.persistence.tables.records.GeneroRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genero extends TableImpl<GeneroRecord> {

    private static final long serialVersionUID = 1166739206;

    /**
     * The reference instance of <code>bd_sica_movie.genero</code>
     */
    public static final Genero GENERO = new Genero();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneroRecord> getRecordType() {
        return GeneroRecord.class;
    }

    /**
     * The column <code>bd_sica_movie.genero.id</code>.
     */
    public final TableField<GeneroRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bd_sica_movie.genero.descricao</code>.
     */
    public final TableField<GeneroRecord, String> DESCRICAO = createField(DSL.name("descricao"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>bd_sica_movie.genero</code> table reference
     */
    public Genero() {
        this(DSL.name("genero"), null);
    }

    /**
     * Create an aliased <code>bd_sica_movie.genero</code> table reference
     */
    public Genero(String alias) {
        this(DSL.name(alias), GENERO);
    }

    /**
     * Create an aliased <code>bd_sica_movie.genero</code> table reference
     */
    public Genero(Name alias) {
        this(alias, GENERO);
    }

    private Genero(Name alias, Table<GeneroRecord> aliased) {
        this(alias, aliased, null);
    }

    private Genero(Name alias, Table<GeneroRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Genero(Table<O> child, ForeignKey<O, GeneroRecord> key) {
        super(child, key, GENERO);
    }

    @Override
    public Schema getSchema() {
        return BdSicaMovie.BD_SICA_MOVIE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GENERO_PRIMARY);
    }

    @Override
    public Identity<GeneroRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GENERO;
    }

    @Override
    public UniqueKey<GeneroRecord> getPrimaryKey() {
        return Keys.KEY_GENERO_PRIMARY;
    }

    @Override
    public List<UniqueKey<GeneroRecord>> getKeys() {
        return Arrays.<UniqueKey<GeneroRecord>>asList(Keys.KEY_GENERO_PRIMARY);
    }

    @Override
    public Genero as(String alias) {
        return new Genero(DSL.name(alias), this);
    }

    @Override
    public Genero as(Name alias) {
        return new Genero(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Genero rename(String name) {
        return new Genero(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genero rename(Name name) {
        return new Genero(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
