/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables;


import br.edu.uni7.sicamovie.persistence.BdSicaMovie;
import br.edu.uni7.sicamovie.persistence.Indexes;
import br.edu.uni7.sicamovie.persistence.Keys;
import br.edu.uni7.sicamovie.persistence.tables.records.HorarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Horario extends TableImpl<HorarioRecord> {

    private static final long serialVersionUID = -101905274;

    /**
     * The reference instance of <code>bd_sica_movie.horario</code>
     */
    public static final Horario HORARIO = new Horario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HorarioRecord> getRecordType() {
        return HorarioRecord.class;
    }

    /**
     * The column <code>bd_sica_movie.horario.id</code>.
     */
    public final TableField<HorarioRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bd_sica_movie.horario.descricao</code>.
     */
    public final TableField<HorarioRecord, String> DESCRICAO = createField(DSL.name("descricao"), org.jooq.impl.SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * Create a <code>bd_sica_movie.horario</code> table reference
     */
    public Horario() {
        this(DSL.name("horario"), null);
    }

    /**
     * Create an aliased <code>bd_sica_movie.horario</code> table reference
     */
    public Horario(String alias) {
        this(DSL.name(alias), HORARIO);
    }

    /**
     * Create an aliased <code>bd_sica_movie.horario</code> table reference
     */
    public Horario(Name alias) {
        this(alias, HORARIO);
    }

    private Horario(Name alias, Table<HorarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private Horario(Name alias, Table<HorarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Horario(Table<O> child, ForeignKey<O, HorarioRecord> key) {
        super(child, key, HORARIO);
    }

    @Override
    public Schema getSchema() {
        return BdSicaMovie.BD_SICA_MOVIE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HORARIO_PRIMARY);
    }

    @Override
    public Identity<HorarioRecord, Integer> getIdentity() {
        return Keys.IDENTITY_HORARIO;
    }

    @Override
    public UniqueKey<HorarioRecord> getPrimaryKey() {
        return Keys.KEY_HORARIO_PRIMARY;
    }

    @Override
    public List<UniqueKey<HorarioRecord>> getKeys() {
        return Arrays.<UniqueKey<HorarioRecord>>asList(Keys.KEY_HORARIO_PRIMARY);
    }

    @Override
    public Horario as(String alias) {
        return new Horario(DSL.name(alias), this);
    }

    @Override
    public Horario as(Name alias) {
        return new Horario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Horario rename(String name) {
        return new Horario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Horario rename(Name name) {
        return new Horario(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
