/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables.records;


import br.edu.uni7.sicamovie.persistence.tables.Filme;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmeRecord extends UpdatableRecordImpl<FilmeRecord> implements Record7<Integer, String, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = -43436651;

    /**
     * Setter for <code>bd_sica_movie.filme.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.nome_pt</code>.
     */
    public void setNomePt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.nome_pt</code>.
     */
    public String getNomePt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.nome_or</code>.
     */
    public void setNomeOr(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.nome_or</code>.
     */
    public String getNomeOr() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.ano_lancamento</code>.
     */
    public void setAnoLancamento(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.ano_lancamento</code>.
     */
    public String getAnoLancamento() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.sinopse</code>.
     */
    public void setSinopse(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.sinopse</code>.
     */
    public String getSinopse() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.diretor_id</code>.
     */
    public void setDiretorId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.diretor_id</code>.
     */
    public Integer getDiretorId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bd_sica_movie.filme.tipo_id</code>.
     */
    public void setTipoId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme.tipo_id</code>.
     */
    public Integer getTipoId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Filme.FILME.ID;
    }

    @Override
    public Field<String> field2() {
        return Filme.FILME.NOME_PT;
    }

    @Override
    public Field<String> field3() {
        return Filme.FILME.NOME_OR;
    }

    @Override
    public Field<String> field4() {
        return Filme.FILME.ANO_LANCAMENTO;
    }

    @Override
    public Field<String> field5() {
        return Filme.FILME.SINOPSE;
    }

    @Override
    public Field<Integer> field6() {
        return Filme.FILME.DIRETOR_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Filme.FILME.TIPO_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNomePt();
    }

    @Override
    public String component3() {
        return getNomeOr();
    }

    @Override
    public String component4() {
        return getAnoLancamento();
    }

    @Override
    public String component5() {
        return getSinopse();
    }

    @Override
    public Integer component6() {
        return getDiretorId();
    }

    @Override
    public Integer component7() {
        return getTipoId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNomePt();
    }

    @Override
    public String value3() {
        return getNomeOr();
    }

    @Override
    public String value4() {
        return getAnoLancamento();
    }

    @Override
    public String value5() {
        return getSinopse();
    }

    @Override
    public Integer value6() {
        return getDiretorId();
    }

    @Override
    public Integer value7() {
        return getTipoId();
    }

    @Override
    public FilmeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FilmeRecord value2(String value) {
        setNomePt(value);
        return this;
    }

    @Override
    public FilmeRecord value3(String value) {
        setNomeOr(value);
        return this;
    }

    @Override
    public FilmeRecord value4(String value) {
        setAnoLancamento(value);
        return this;
    }

    @Override
    public FilmeRecord value5(String value) {
        setSinopse(value);
        return this;
    }

    @Override
    public FilmeRecord value6(Integer value) {
        setDiretorId(value);
        return this;
    }

    @Override
    public FilmeRecord value7(Integer value) {
        setTipoId(value);
        return this;
    }

    @Override
    public FilmeRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmeRecord
     */
    public FilmeRecord() {
        super(Filme.FILME);
    }

    /**
     * Create a detached, initialised FilmeRecord
     */
    public FilmeRecord(Integer id, String nomePt, String nomeOr, String anoLancamento, String sinopse, Integer diretorId, Integer tipoId) {
        super(Filme.FILME);

        set(0, id);
        set(1, nomePt);
        set(2, nomeOr);
        set(3, anoLancamento);
        set(4, sinopse);
        set(5, diretorId);
        set(6, tipoId);
    }
}
