/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables.records;


import br.edu.uni7.sicamovie.persistence.tables.FilmePremio;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmePremioRecord extends UpdatableRecordImpl<FilmePremioRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -599216381;

    /**
     * Setter for <code>bd_sica_movie.filme_premio.filme_id</code>.
     */
    public void setFilmeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme_premio.filme_id</code>.
     */
    public Integer getFilmeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bd_sica_movie.filme_premio.premio_id</code>.
     */
    public void setPremioId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bd_sica_movie.filme_premio.premio_id</code>.
     */
    public Integer getPremioId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FilmePremio.FILME_PREMIO.FILME_ID;
    }

    @Override
    public Field<Integer> field2() {
        return FilmePremio.FILME_PREMIO.PREMIO_ID;
    }

    @Override
    public Integer component1() {
        return getFilmeId();
    }

    @Override
    public Integer component2() {
        return getPremioId();
    }

    @Override
    public Integer value1() {
        return getFilmeId();
    }

    @Override
    public Integer value2() {
        return getPremioId();
    }

    @Override
    public FilmePremioRecord value1(Integer value) {
        setFilmeId(value);
        return this;
    }

    @Override
    public FilmePremioRecord value2(Integer value) {
        setPremioId(value);
        return this;
    }

    @Override
    public FilmePremioRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmePremioRecord
     */
    public FilmePremioRecord() {
        super(FilmePremio.FILME_PREMIO);
    }

    /**
     * Create a detached, initialised FilmePremioRecord
     */
    public FilmePremioRecord(Integer filmeId, Integer premioId) {
        super(FilmePremio.FILME_PREMIO);

        set(0, filmeId);
        set(1, premioId);
    }
}
