/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables.records;


import br.edu.uni7.sicamovie.persistence.tables.Premio;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PremioRecord extends UpdatableRecordImpl<PremioRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -65518803;

    /**
     * Setter for <code>bd_sica_movie.premio.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bd_sica_movie.premio.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bd_sica_movie.premio.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bd_sica_movie.premio.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bd_sica_movie.premio.descricao</code>.
     */
    public void setDescricao(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bd_sica_movie.premio.descricao</code>.
     */
    public String getDescricao() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bd_sica_movie.premio.ano_premiacao</code>.
     */
    public void setAnoPremiacao(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bd_sica_movie.premio.ano_premiacao</code>.
     */
    public String getAnoPremiacao() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Premio.PREMIO.ID;
    }

    @Override
    public Field<String> field2() {
        return Premio.PREMIO.NOME;
    }

    @Override
    public Field<String> field3() {
        return Premio.PREMIO.DESCRICAO;
    }

    @Override
    public Field<String> field4() {
        return Premio.PREMIO.ANO_PREMIACAO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNome();
    }

    @Override
    public String component3() {
        return getDescricao();
    }

    @Override
    public String component4() {
        return getAnoPremiacao();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNome();
    }

    @Override
    public String value3() {
        return getDescricao();
    }

    @Override
    public String value4() {
        return getAnoPremiacao();
    }

    @Override
    public PremioRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PremioRecord value2(String value) {
        setNome(value);
        return this;
    }

    @Override
    public PremioRecord value3(String value) {
        setDescricao(value);
        return this;
    }

    @Override
    public PremioRecord value4(String value) {
        setAnoPremiacao(value);
        return this;
    }

    @Override
    public PremioRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PremioRecord
     */
    public PremioRecord() {
        super(Premio.PREMIO);
    }

    /**
     * Create a detached, initialised PremioRecord
     */
    public PremioRecord(Integer id, String nome, String descricao, String anoPremiacao) {
        super(Premio.PREMIO);

        set(0, id);
        set(1, nome);
        set(2, descricao);
        set(3, anoPremiacao);
    }
}
