/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence.tables.records;


import br.edu.uni7.sicamovie.persistence.tables.Sessao;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessaoRecord extends UpdatableRecordImpl<SessaoRecord> implements Record5<Integer, Date, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1277852278;

    /**
     * Setter for <code>bd_sica_movie.sessao.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bd_sica_movie.sessao.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bd_sica_movie.sessao.dia</code>.
     */
    public void setDia(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>bd_sica_movie.sessao.dia</code>.
     */
    public Date getDia() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>bd_sica_movie.sessao.filme_id</code>.
     */
    public void setFilmeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bd_sica_movie.sessao.filme_id</code>.
     */
    public Integer getFilmeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bd_sica_movie.sessao.sala_id</code>.
     */
    public void setSalaId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bd_sica_movie.sessao.sala_id</code>.
     */
    public Integer getSalaId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bd_sica_movie.sessao.horario_id</code>.
     */
    public void setHorarioId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>bd_sica_movie.sessao.horario_id</code>.
     */
    public Integer getHorarioId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Date, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Date, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sessao.SESSAO.ID;
    }

    @Override
    public Field<Date> field2() {
        return Sessao.SESSAO.DIA;
    }

    @Override
    public Field<Integer> field3() {
        return Sessao.SESSAO.FILME_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Sessao.SESSAO.SALA_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Sessao.SESSAO.HORARIO_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Date component2() {
        return getDia();
    }

    @Override
    public Integer component3() {
        return getFilmeId();
    }

    @Override
    public Integer component4() {
        return getSalaId();
    }

    @Override
    public Integer component5() {
        return getHorarioId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Date value2() {
        return getDia();
    }

    @Override
    public Integer value3() {
        return getFilmeId();
    }

    @Override
    public Integer value4() {
        return getSalaId();
    }

    @Override
    public Integer value5() {
        return getHorarioId();
    }

    @Override
    public SessaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SessaoRecord value2(Date value) {
        setDia(value);
        return this;
    }

    @Override
    public SessaoRecord value3(Integer value) {
        setFilmeId(value);
        return this;
    }

    @Override
    public SessaoRecord value4(Integer value) {
        setSalaId(value);
        return this;
    }

    @Override
    public SessaoRecord value5(Integer value) {
        setHorarioId(value);
        return this;
    }

    @Override
    public SessaoRecord values(Integer value1, Date value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessaoRecord
     */
    public SessaoRecord() {
        super(Sessao.SESSAO);
    }

    /**
     * Create a detached, initialised SessaoRecord
     */
    public SessaoRecord(Integer id, Date dia, Integer filmeId, Integer salaId, Integer horarioId) {
        super(Sessao.SESSAO);

        set(0, id);
        set(1, dia);
        set(2, filmeId);
        set(3, salaId);
        set(4, horarioId);
    }
}
