/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence;


import br.edu.uni7.sicamovie.persistence.tables.Diretor;
import br.edu.uni7.sicamovie.persistence.tables.Filme;
import br.edu.uni7.sicamovie.persistence.tables.FilmePremio;
import br.edu.uni7.sicamovie.persistence.tables.Funcao;
import br.edu.uni7.sicamovie.persistence.tables.Funcionario;
import br.edu.uni7.sicamovie.persistence.tables.FuncionarioHorario;
import br.edu.uni7.sicamovie.persistence.tables.Genero;
import br.edu.uni7.sicamovie.persistence.tables.Horario;
import br.edu.uni7.sicamovie.persistence.tables.Ingresso;
import br.edu.uni7.sicamovie.persistence.tables.Localizacao;
import br.edu.uni7.sicamovie.persistence.tables.Premio;
import br.edu.uni7.sicamovie.persistence.tables.Sala;
import br.edu.uni7.sicamovie.persistence.tables.Sessao;
import br.edu.uni7.sicamovie.persistence.tables.TipoIngresso;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BdSicaMovie extends SchemaImpl {

    private static final long serialVersionUID = -1142847559;

    /**
     * The reference instance of <code>bd_sica_movie</code>
     */
    public static final BdSicaMovie BD_SICA_MOVIE = new BdSicaMovie();

    /**
     * The table <code>bd_sica_movie.diretor</code>.
     */
    public final Diretor DIRETOR = br.edu.uni7.sicamovie.persistence.tables.Diretor.DIRETOR;

    /**
     * The table <code>bd_sica_movie.filme</code>.
     */
    public final Filme FILME = br.edu.uni7.sicamovie.persistence.tables.Filme.FILME;

    /**
     * The table <code>bd_sica_movie.filme_premio</code>.
     */
    public final FilmePremio FILME_PREMIO = br.edu.uni7.sicamovie.persistence.tables.FilmePremio.FILME_PREMIO;

    /**
     * The table <code>bd_sica_movie.funcao</code>.
     */
    public final Funcao FUNCAO = br.edu.uni7.sicamovie.persistence.tables.Funcao.FUNCAO;

    /**
     * The table <code>bd_sica_movie.funcionario</code>.
     */
    public final Funcionario FUNCIONARIO = br.edu.uni7.sicamovie.persistence.tables.Funcionario.FUNCIONARIO;

    /**
     * The table <code>bd_sica_movie.funcionario_horario</code>.
     */
    public final FuncionarioHorario FUNCIONARIO_HORARIO = br.edu.uni7.sicamovie.persistence.tables.FuncionarioHorario.FUNCIONARIO_HORARIO;

    /**
     * The table <code>bd_sica_movie.genero</code>.
     */
    public final Genero GENERO = br.edu.uni7.sicamovie.persistence.tables.Genero.GENERO;

    /**
     * The table <code>bd_sica_movie.horario</code>.
     */
    public final Horario HORARIO = br.edu.uni7.sicamovie.persistence.tables.Horario.HORARIO;

    /**
     * The table <code>bd_sica_movie.ingresso</code>.
     */
    public final Ingresso INGRESSO = br.edu.uni7.sicamovie.persistence.tables.Ingresso.INGRESSO;

    /**
     * The table <code>bd_sica_movie.localizacao</code>.
     */
    public final Localizacao LOCALIZACAO = br.edu.uni7.sicamovie.persistence.tables.Localizacao.LOCALIZACAO;

    /**
     * The table <code>bd_sica_movie.premio</code>.
     */
    public final Premio PREMIO = br.edu.uni7.sicamovie.persistence.tables.Premio.PREMIO;

    /**
     * The table <code>bd_sica_movie.sala</code>.
     */
    public final Sala SALA = br.edu.uni7.sicamovie.persistence.tables.Sala.SALA;

    /**
     * The table <code>bd_sica_movie.sessao</code>.
     */
    public final Sessao SESSAO = br.edu.uni7.sicamovie.persistence.tables.Sessao.SESSAO;

    /**
     * The table <code>bd_sica_movie.tipo_ingresso</code>.
     */
    public final TipoIngresso TIPO_INGRESSO = br.edu.uni7.sicamovie.persistence.tables.TipoIngresso.TIPO_INGRESSO;

    /**
     * No further instances allowed
     */
    private BdSicaMovie() {
        super("bd_sica_movie", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Diretor.DIRETOR,
            Filme.FILME,
            FilmePremio.FILME_PREMIO,
            Funcao.FUNCAO,
            Funcionario.FUNCIONARIO,
            FuncionarioHorario.FUNCIONARIO_HORARIO,
            Genero.GENERO,
            Horario.HORARIO,
            Ingresso.INGRESSO,
            Localizacao.LOCALIZACAO,
            Premio.PREMIO,
            Sala.SALA,
            Sessao.SESSAO,
            TipoIngresso.TIPO_INGRESSO);
    }
}
