/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence;


import br.edu.uni7.sicamovie.persistence.tables.Diretor;
import br.edu.uni7.sicamovie.persistence.tables.Filme;
import br.edu.uni7.sicamovie.persistence.tables.FilmePremio;
import br.edu.uni7.sicamovie.persistence.tables.Funcao;
import br.edu.uni7.sicamovie.persistence.tables.Funcionario;
import br.edu.uni7.sicamovie.persistence.tables.FuncionarioHorario;
import br.edu.uni7.sicamovie.persistence.tables.Genero;
import br.edu.uni7.sicamovie.persistence.tables.Horario;
import br.edu.uni7.sicamovie.persistence.tables.Ingresso;
import br.edu.uni7.sicamovie.persistence.tables.Localizacao;
import br.edu.uni7.sicamovie.persistence.tables.Premio;
import br.edu.uni7.sicamovie.persistence.tables.Sala;
import br.edu.uni7.sicamovie.persistence.tables.Sessao;
import br.edu.uni7.sicamovie.persistence.tables.TipoIngresso;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bd_sica_movie</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DIRETOR_PRIMARY = Indexes0.DIRETOR_PRIMARY;
    public static final Index FILME_FK_FILME_DIRETOR_ID = Indexes0.FILME_FK_FILME_DIRETOR_ID;
    public static final Index FILME_FK_FILME_TIPO_ID = Indexes0.FILME_FK_FILME_TIPO_ID;
    public static final Index FILME_PRIMARY = Indexes0.FILME_PRIMARY;
    public static final Index FILME_PREMIO_FK_FILMEPREMIO_PREMIO_ID = Indexes0.FILME_PREMIO_FK_FILMEPREMIO_PREMIO_ID;
    public static final Index FILME_PREMIO_PRIMARY = Indexes0.FILME_PREMIO_PRIMARY;
    public static final Index FUNCAO_PRIMARY = Indexes0.FUNCAO_PRIMARY;
    public static final Index FUNCIONARIO_FK_FUNCIONARIO_FUNCAO_ID = Indexes0.FUNCIONARIO_FK_FUNCIONARIO_FUNCAO_ID;
    public static final Index FUNCIONARIO_FK_FUNCIONARIO_LOCALIZACAO_ID = Indexes0.FUNCIONARIO_FK_FUNCIONARIO_LOCALIZACAO_ID;
    public static final Index FUNCIONARIO_PRIMARY = Indexes0.FUNCIONARIO_PRIMARY;
    public static final Index FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA = Indexes0.FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA;
    public static final Index FUNCIONARIO_HORARIO_FK_FILMEHORARIO_HORARIO_ID = Indexes0.FUNCIONARIO_HORARIO_FK_FILMEHORARIO_HORARIO_ID;
    public static final Index FUNCIONARIO_HORARIO_PRIMARY = Indexes0.FUNCIONARIO_HORARIO_PRIMARY;
    public static final Index GENERO_PRIMARY = Indexes0.GENERO_PRIMARY;
    public static final Index HORARIO_PRIMARY = Indexes0.HORARIO_PRIMARY;
    public static final Index INGRESSO_FK_INGRESSO_SESSAO_ID = Indexes0.INGRESSO_FK_INGRESSO_SESSAO_ID;
    public static final Index INGRESSO_FK_INGRESSO_TIPOINGRESSO_ID = Indexes0.INGRESSO_FK_INGRESSO_TIPOINGRESSO_ID;
    public static final Index INGRESSO_PRIMARY = Indexes0.INGRESSO_PRIMARY;
    public static final Index LOCALIZACAO_PRIMARY = Indexes0.LOCALIZACAO_PRIMARY;
    public static final Index PREMIO_PRIMARY = Indexes0.PREMIO_PRIMARY;
    public static final Index SALA_FK_SALA_LOCALIZACAO_ID = Indexes0.SALA_FK_SALA_LOCALIZACAO_ID;
    public static final Index SALA_PRIMARY = Indexes0.SALA_PRIMARY;
    public static final Index SESSAO_FK_SESSAO_FILME_ID = Indexes0.SESSAO_FK_SESSAO_FILME_ID;
    public static final Index SESSAO_FK_SESSAO_HORARIO_ID = Indexes0.SESSAO_FK_SESSAO_HORARIO_ID;
    public static final Index SESSAO_FK_SESSAO_SALA_ID = Indexes0.SESSAO_FK_SESSAO_SALA_ID;
    public static final Index SESSAO_PRIMARY = Indexes0.SESSAO_PRIMARY;
    public static final Index TIPO_INGRESSO_PRIMARY = Indexes0.TIPO_INGRESSO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DIRETOR_PRIMARY = Internal.createIndex("PRIMARY", Diretor.DIRETOR, new OrderField[] { Diretor.DIRETOR.ID }, true);
        public static Index FILME_FK_FILME_DIRETOR_ID = Internal.createIndex("fk_filme_diretor_id", Filme.FILME, new OrderField[] { Filme.FILME.DIRETOR_ID }, false);
        public static Index FILME_FK_FILME_TIPO_ID = Internal.createIndex("fk_filme_tipo_id", Filme.FILME, new OrderField[] { Filme.FILME.TIPO_ID }, false);
        public static Index FILME_PRIMARY = Internal.createIndex("PRIMARY", Filme.FILME, new OrderField[] { Filme.FILME.ID }, true);
        public static Index FILME_PREMIO_FK_FILMEPREMIO_PREMIO_ID = Internal.createIndex("fk_filmepremio_premio_id", FilmePremio.FILME_PREMIO, new OrderField[] { FilmePremio.FILME_PREMIO.PREMIO_ID }, false);
        public static Index FILME_PREMIO_PRIMARY = Internal.createIndex("PRIMARY", FilmePremio.FILME_PREMIO, new OrderField[] { FilmePremio.FILME_PREMIO.FILME_ID, FilmePremio.FILME_PREMIO.PREMIO_ID }, true);
        public static Index FUNCAO_PRIMARY = Internal.createIndex("PRIMARY", Funcao.FUNCAO, new OrderField[] { Funcao.FUNCAO.ID }, true);
        public static Index FUNCIONARIO_FK_FUNCIONARIO_FUNCAO_ID = Internal.createIndex("fk_funcionario_funcao_id", Funcionario.FUNCIONARIO, new OrderField[] { Funcionario.FUNCIONARIO.FUNCAO_ID }, false);
        public static Index FUNCIONARIO_FK_FUNCIONARIO_LOCALIZACAO_ID = Internal.createIndex("fk_funcionario_localizacao_id", Funcionario.FUNCIONARIO, new OrderField[] { Funcionario.FUNCIONARIO.LOCALIZACAO_ID }, false);
        public static Index FUNCIONARIO_PRIMARY = Internal.createIndex("PRIMARY", Funcionario.FUNCIONARIO, new OrderField[] { Funcionario.FUNCIONARIO.ID }, true);
        public static Index FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA = Internal.createIndex("uq_funcionario_matricula", Funcionario.FUNCIONARIO, new OrderField[] { Funcionario.FUNCIONARIO.MATRICULA }, true);
        public static Index FUNCIONARIO_HORARIO_FK_FILMEHORARIO_HORARIO_ID = Internal.createIndex("fk_filmehorario_horario_id", FuncionarioHorario.FUNCIONARIO_HORARIO, new OrderField[] { FuncionarioHorario.FUNCIONARIO_HORARIO.HORARIO_ID }, false);
        public static Index FUNCIONARIO_HORARIO_PRIMARY = Internal.createIndex("PRIMARY", FuncionarioHorario.FUNCIONARIO_HORARIO, new OrderField[] { FuncionarioHorario.FUNCIONARIO_HORARIO.FUNCIONARIO_ID, FuncionarioHorario.FUNCIONARIO_HORARIO.HORARIO_ID }, true);
        public static Index GENERO_PRIMARY = Internal.createIndex("PRIMARY", Genero.GENERO, new OrderField[] { Genero.GENERO.ID }, true);
        public static Index HORARIO_PRIMARY = Internal.createIndex("PRIMARY", Horario.HORARIO, new OrderField[] { Horario.HORARIO.ID }, true);
        public static Index INGRESSO_FK_INGRESSO_SESSAO_ID = Internal.createIndex("fk_ingresso_sessao_id", Ingresso.INGRESSO, new OrderField[] { Ingresso.INGRESSO.SESSAO_ID }, false);
        public static Index INGRESSO_FK_INGRESSO_TIPOINGRESSO_ID = Internal.createIndex("fk_ingresso_tipoingresso_id", Ingresso.INGRESSO, new OrderField[] { Ingresso.INGRESSO.TIPO_INGRESSO }, false);
        public static Index INGRESSO_PRIMARY = Internal.createIndex("PRIMARY", Ingresso.INGRESSO, new OrderField[] { Ingresso.INGRESSO.ID }, true);
        public static Index LOCALIZACAO_PRIMARY = Internal.createIndex("PRIMARY", Localizacao.LOCALIZACAO, new OrderField[] { Localizacao.LOCALIZACAO.ID }, true);
        public static Index PREMIO_PRIMARY = Internal.createIndex("PRIMARY", Premio.PREMIO, new OrderField[] { Premio.PREMIO.ID }, true);
        public static Index SALA_FK_SALA_LOCALIZACAO_ID = Internal.createIndex("fk_sala_localizacao_id", Sala.SALA, new OrderField[] { Sala.SALA.LOCALIZACAO_ID }, false);
        public static Index SALA_PRIMARY = Internal.createIndex("PRIMARY", Sala.SALA, new OrderField[] { Sala.SALA.ID }, true);
        public static Index SESSAO_FK_SESSAO_FILME_ID = Internal.createIndex("fk_sessao_filme_id", Sessao.SESSAO, new OrderField[] { Sessao.SESSAO.FILME_ID }, false);
        public static Index SESSAO_FK_SESSAO_HORARIO_ID = Internal.createIndex("fk_sessao_horario_id", Sessao.SESSAO, new OrderField[] { Sessao.SESSAO.HORARIO_ID }, false);
        public static Index SESSAO_FK_SESSAO_SALA_ID = Internal.createIndex("fk_sessao_sala_id", Sessao.SESSAO, new OrderField[] { Sessao.SESSAO.SALA_ID }, false);
        public static Index SESSAO_PRIMARY = Internal.createIndex("PRIMARY", Sessao.SESSAO, new OrderField[] { Sessao.SESSAO.ID }, true);
        public static Index TIPO_INGRESSO_PRIMARY = Internal.createIndex("PRIMARY", TipoIngresso.TIPO_INGRESSO, new OrderField[] { TipoIngresso.TIPO_INGRESSO.ID }, true);
    }
}
