/*
 * This file is generated by jOOQ.
 */
package br.edu.uni7.sicamovie.persistence;


import br.edu.uni7.sicamovie.persistence.tables.Diretor;
import br.edu.uni7.sicamovie.persistence.tables.Filme;
import br.edu.uni7.sicamovie.persistence.tables.FilmePremio;
import br.edu.uni7.sicamovie.persistence.tables.Funcao;
import br.edu.uni7.sicamovie.persistence.tables.Funcionario;
import br.edu.uni7.sicamovie.persistence.tables.FuncionarioHorario;
import br.edu.uni7.sicamovie.persistence.tables.Genero;
import br.edu.uni7.sicamovie.persistence.tables.Horario;
import br.edu.uni7.sicamovie.persistence.tables.Ingresso;
import br.edu.uni7.sicamovie.persistence.tables.Localizacao;
import br.edu.uni7.sicamovie.persistence.tables.Premio;
import br.edu.uni7.sicamovie.persistence.tables.Sala;
import br.edu.uni7.sicamovie.persistence.tables.Sessao;
import br.edu.uni7.sicamovie.persistence.tables.TipoIngresso;
import br.edu.uni7.sicamovie.persistence.tables.records.DiretorRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.FilmePremioRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.FilmeRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.FuncaoRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.FuncionarioHorarioRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.FuncionarioRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.GeneroRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.HorarioRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.IngressoRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.LocalizacaoRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.PremioRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.SalaRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.SessaoRecord;
import br.edu.uni7.sicamovie.persistence.tables.records.TipoIngressoRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>bd_sica_movie</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DiretorRecord, Integer> IDENTITY_DIRETOR = Identities0.IDENTITY_DIRETOR;
    public static final Identity<FilmeRecord, Integer> IDENTITY_FILME = Identities0.IDENTITY_FILME;
    public static final Identity<FuncaoRecord, Integer> IDENTITY_FUNCAO = Identities0.IDENTITY_FUNCAO;
    public static final Identity<FuncionarioRecord, Integer> IDENTITY_FUNCIONARIO = Identities0.IDENTITY_FUNCIONARIO;
    public static final Identity<GeneroRecord, Integer> IDENTITY_GENERO = Identities0.IDENTITY_GENERO;
    public static final Identity<HorarioRecord, Integer> IDENTITY_HORARIO = Identities0.IDENTITY_HORARIO;
    public static final Identity<IngressoRecord, Integer> IDENTITY_INGRESSO = Identities0.IDENTITY_INGRESSO;
    public static final Identity<LocalizacaoRecord, Integer> IDENTITY_LOCALIZACAO = Identities0.IDENTITY_LOCALIZACAO;
    public static final Identity<PremioRecord, Integer> IDENTITY_PREMIO = Identities0.IDENTITY_PREMIO;
    public static final Identity<SalaRecord, Integer> IDENTITY_SALA = Identities0.IDENTITY_SALA;
    public static final Identity<SessaoRecord, Integer> IDENTITY_SESSAO = Identities0.IDENTITY_SESSAO;
    public static final Identity<TipoIngressoRecord, Integer> IDENTITY_TIPO_INGRESSO = Identities0.IDENTITY_TIPO_INGRESSO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DiretorRecord> KEY_DIRETOR_PRIMARY = UniqueKeys0.KEY_DIRETOR_PRIMARY;
    public static final UniqueKey<FilmeRecord> KEY_FILME_PRIMARY = UniqueKeys0.KEY_FILME_PRIMARY;
    public static final UniqueKey<FilmePremioRecord> KEY_FILME_PREMIO_PRIMARY = UniqueKeys0.KEY_FILME_PREMIO_PRIMARY;
    public static final UniqueKey<FuncaoRecord> KEY_FUNCAO_PRIMARY = UniqueKeys0.KEY_FUNCAO_PRIMARY;
    public static final UniqueKey<FuncionarioRecord> KEY_FUNCIONARIO_PRIMARY = UniqueKeys0.KEY_FUNCIONARIO_PRIMARY;
    public static final UniqueKey<FuncionarioRecord> KEY_FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA = UniqueKeys0.KEY_FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA;
    public static final UniqueKey<FuncionarioHorarioRecord> KEY_FUNCIONARIO_HORARIO_PRIMARY = UniqueKeys0.KEY_FUNCIONARIO_HORARIO_PRIMARY;
    public static final UniqueKey<GeneroRecord> KEY_GENERO_PRIMARY = UniqueKeys0.KEY_GENERO_PRIMARY;
    public static final UniqueKey<HorarioRecord> KEY_HORARIO_PRIMARY = UniqueKeys0.KEY_HORARIO_PRIMARY;
    public static final UniqueKey<IngressoRecord> KEY_INGRESSO_PRIMARY = UniqueKeys0.KEY_INGRESSO_PRIMARY;
    public static final UniqueKey<LocalizacaoRecord> KEY_LOCALIZACAO_PRIMARY = UniqueKeys0.KEY_LOCALIZACAO_PRIMARY;
    public static final UniqueKey<PremioRecord> KEY_PREMIO_PRIMARY = UniqueKeys0.KEY_PREMIO_PRIMARY;
    public static final UniqueKey<SalaRecord> KEY_SALA_PRIMARY = UniqueKeys0.KEY_SALA_PRIMARY;
    public static final UniqueKey<SessaoRecord> KEY_SESSAO_PRIMARY = UniqueKeys0.KEY_SESSAO_PRIMARY;
    public static final UniqueKey<TipoIngressoRecord> KEY_TIPO_INGRESSO_PRIMARY = UniqueKeys0.KEY_TIPO_INGRESSO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FilmeRecord, DiretorRecord> FK_FILME_DIRETOR_ID = ForeignKeys0.FK_FILME_DIRETOR_ID;
    public static final ForeignKey<FilmeRecord, GeneroRecord> FK_FILME_TIPO_ID = ForeignKeys0.FK_FILME_TIPO_ID;
    public static final ForeignKey<FilmePremioRecord, FilmeRecord> FK_FILMEPREMIO_FILME_ID = ForeignKeys0.FK_FILMEPREMIO_FILME_ID;
    public static final ForeignKey<FilmePremioRecord, PremioRecord> FK_FILMEPREMIO_PREMIO_ID = ForeignKeys0.FK_FILMEPREMIO_PREMIO_ID;
    public static final ForeignKey<FuncionarioRecord, FuncaoRecord> FK_FUNCIONARIO_FUNCAO_ID = ForeignKeys0.FK_FUNCIONARIO_FUNCAO_ID;
    public static final ForeignKey<FuncionarioRecord, LocalizacaoRecord> FK_FUNCIONARIO_LOCALIZACAO_ID = ForeignKeys0.FK_FUNCIONARIO_LOCALIZACAO_ID;
    public static final ForeignKey<FuncionarioHorarioRecord, FuncionarioRecord> FK_FUNCIONARIOHORARIO_FUNCIONARIO_ID = ForeignKeys0.FK_FUNCIONARIOHORARIO_FUNCIONARIO_ID;
    public static final ForeignKey<FuncionarioHorarioRecord, HorarioRecord> FK_FILMEHORARIO_HORARIO_ID = ForeignKeys0.FK_FILMEHORARIO_HORARIO_ID;
    public static final ForeignKey<IngressoRecord, SessaoRecord> FK_INGRESSO_SESSAO_ID = ForeignKeys0.FK_INGRESSO_SESSAO_ID;
    public static final ForeignKey<IngressoRecord, TipoIngressoRecord> FK_INGRESSO_TIPOINGRESSO_ID = ForeignKeys0.FK_INGRESSO_TIPOINGRESSO_ID;
    public static final ForeignKey<SalaRecord, LocalizacaoRecord> FK_SALA_LOCALIZACAO_ID = ForeignKeys0.FK_SALA_LOCALIZACAO_ID;
    public static final ForeignKey<SessaoRecord, FilmeRecord> FK_SESSAO_FILME_ID = ForeignKeys0.FK_SESSAO_FILME_ID;
    public static final ForeignKey<SessaoRecord, SalaRecord> FK_SESSAO_SALA_ID = ForeignKeys0.FK_SESSAO_SALA_ID;
    public static final ForeignKey<SessaoRecord, HorarioRecord> FK_SESSAO_HORARIO_ID = ForeignKeys0.FK_SESSAO_HORARIO_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DiretorRecord, Integer> IDENTITY_DIRETOR = Internal.createIdentity(Diretor.DIRETOR, Diretor.DIRETOR.ID);
        public static Identity<FilmeRecord, Integer> IDENTITY_FILME = Internal.createIdentity(Filme.FILME, Filme.FILME.ID);
        public static Identity<FuncaoRecord, Integer> IDENTITY_FUNCAO = Internal.createIdentity(Funcao.FUNCAO, Funcao.FUNCAO.ID);
        public static Identity<FuncionarioRecord, Integer> IDENTITY_FUNCIONARIO = Internal.createIdentity(Funcionario.FUNCIONARIO, Funcionario.FUNCIONARIO.ID);
        public static Identity<GeneroRecord, Integer> IDENTITY_GENERO = Internal.createIdentity(Genero.GENERO, Genero.GENERO.ID);
        public static Identity<HorarioRecord, Integer> IDENTITY_HORARIO = Internal.createIdentity(Horario.HORARIO, Horario.HORARIO.ID);
        public static Identity<IngressoRecord, Integer> IDENTITY_INGRESSO = Internal.createIdentity(Ingresso.INGRESSO, Ingresso.INGRESSO.ID);
        public static Identity<LocalizacaoRecord, Integer> IDENTITY_LOCALIZACAO = Internal.createIdentity(Localizacao.LOCALIZACAO, Localizacao.LOCALIZACAO.ID);
        public static Identity<PremioRecord, Integer> IDENTITY_PREMIO = Internal.createIdentity(Premio.PREMIO, Premio.PREMIO.ID);
        public static Identity<SalaRecord, Integer> IDENTITY_SALA = Internal.createIdentity(Sala.SALA, Sala.SALA.ID);
        public static Identity<SessaoRecord, Integer> IDENTITY_SESSAO = Internal.createIdentity(Sessao.SESSAO, Sessao.SESSAO.ID);
        public static Identity<TipoIngressoRecord, Integer> IDENTITY_TIPO_INGRESSO = Internal.createIdentity(TipoIngresso.TIPO_INGRESSO, TipoIngresso.TIPO_INGRESSO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DiretorRecord> KEY_DIRETOR_PRIMARY = Internal.createUniqueKey(Diretor.DIRETOR, "KEY_diretor_PRIMARY", Diretor.DIRETOR.ID);
        public static final UniqueKey<FilmeRecord> KEY_FILME_PRIMARY = Internal.createUniqueKey(Filme.FILME, "KEY_filme_PRIMARY", Filme.FILME.ID);
        public static final UniqueKey<FilmePremioRecord> KEY_FILME_PREMIO_PRIMARY = Internal.createUniqueKey(FilmePremio.FILME_PREMIO, "KEY_filme_premio_PRIMARY", FilmePremio.FILME_PREMIO.FILME_ID, FilmePremio.FILME_PREMIO.PREMIO_ID);
        public static final UniqueKey<FuncaoRecord> KEY_FUNCAO_PRIMARY = Internal.createUniqueKey(Funcao.FUNCAO, "KEY_funcao_PRIMARY", Funcao.FUNCAO.ID);
        public static final UniqueKey<FuncionarioRecord> KEY_FUNCIONARIO_PRIMARY = Internal.createUniqueKey(Funcionario.FUNCIONARIO, "KEY_funcionario_PRIMARY", Funcionario.FUNCIONARIO.ID);
        public static final UniqueKey<FuncionarioRecord> KEY_FUNCIONARIO_UQ_FUNCIONARIO_MATRICULA = Internal.createUniqueKey(Funcionario.FUNCIONARIO, "KEY_funcionario_uq_funcionario_matricula", Funcionario.FUNCIONARIO.MATRICULA);
        public static final UniqueKey<FuncionarioHorarioRecord> KEY_FUNCIONARIO_HORARIO_PRIMARY = Internal.createUniqueKey(FuncionarioHorario.FUNCIONARIO_HORARIO, "KEY_funcionario_horario_PRIMARY", FuncionarioHorario.FUNCIONARIO_HORARIO.FUNCIONARIO_ID, FuncionarioHorario.FUNCIONARIO_HORARIO.HORARIO_ID);
        public static final UniqueKey<GeneroRecord> KEY_GENERO_PRIMARY = Internal.createUniqueKey(Genero.GENERO, "KEY_genero_PRIMARY", Genero.GENERO.ID);
        public static final UniqueKey<HorarioRecord> KEY_HORARIO_PRIMARY = Internal.createUniqueKey(Horario.HORARIO, "KEY_horario_PRIMARY", Horario.HORARIO.ID);
        public static final UniqueKey<IngressoRecord> KEY_INGRESSO_PRIMARY = Internal.createUniqueKey(Ingresso.INGRESSO, "KEY_ingresso_PRIMARY", Ingresso.INGRESSO.ID);
        public static final UniqueKey<LocalizacaoRecord> KEY_LOCALIZACAO_PRIMARY = Internal.createUniqueKey(Localizacao.LOCALIZACAO, "KEY_localizacao_PRIMARY", Localizacao.LOCALIZACAO.ID);
        public static final UniqueKey<PremioRecord> KEY_PREMIO_PRIMARY = Internal.createUniqueKey(Premio.PREMIO, "KEY_premio_PRIMARY", Premio.PREMIO.ID);
        public static final UniqueKey<SalaRecord> KEY_SALA_PRIMARY = Internal.createUniqueKey(Sala.SALA, "KEY_sala_PRIMARY", Sala.SALA.ID);
        public static final UniqueKey<SessaoRecord> KEY_SESSAO_PRIMARY = Internal.createUniqueKey(Sessao.SESSAO, "KEY_sessao_PRIMARY", Sessao.SESSAO.ID);
        public static final UniqueKey<TipoIngressoRecord> KEY_TIPO_INGRESSO_PRIMARY = Internal.createUniqueKey(TipoIngresso.TIPO_INGRESSO, "KEY_tipo_ingresso_PRIMARY", TipoIngresso.TIPO_INGRESSO.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<FilmeRecord, DiretorRecord> FK_FILME_DIRETOR_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_DIRETOR_PRIMARY, Filme.FILME, "fk_filme_diretor_id", Filme.FILME.DIRETOR_ID);
        public static final ForeignKey<FilmeRecord, GeneroRecord> FK_FILME_TIPO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_GENERO_PRIMARY, Filme.FILME, "fk_filme_tipo_id", Filme.FILME.TIPO_ID);
        public static final ForeignKey<FilmePremioRecord, FilmeRecord> FK_FILMEPREMIO_FILME_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_FILME_PRIMARY, FilmePremio.FILME_PREMIO, "fk_filmepremio_filme_id", FilmePremio.FILME_PREMIO.FILME_ID);
        public static final ForeignKey<FilmePremioRecord, PremioRecord> FK_FILMEPREMIO_PREMIO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_PREMIO_PRIMARY, FilmePremio.FILME_PREMIO, "fk_filmepremio_premio_id", FilmePremio.FILME_PREMIO.PREMIO_ID);
        public static final ForeignKey<FuncionarioRecord, FuncaoRecord> FK_FUNCIONARIO_FUNCAO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_FUNCAO_PRIMARY, Funcionario.FUNCIONARIO, "fk_funcionario_funcao_id", Funcionario.FUNCIONARIO.FUNCAO_ID);
        public static final ForeignKey<FuncionarioRecord, LocalizacaoRecord> FK_FUNCIONARIO_LOCALIZACAO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_LOCALIZACAO_PRIMARY, Funcionario.FUNCIONARIO, "fk_funcionario_localizacao_id", Funcionario.FUNCIONARIO.LOCALIZACAO_ID);
        public static final ForeignKey<FuncionarioHorarioRecord, FuncionarioRecord> FK_FUNCIONARIOHORARIO_FUNCIONARIO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_FUNCIONARIO_PRIMARY, FuncionarioHorario.FUNCIONARIO_HORARIO, "fk_funcionariohorario_funcionario_id", FuncionarioHorario.FUNCIONARIO_HORARIO.FUNCIONARIO_ID);
        public static final ForeignKey<FuncionarioHorarioRecord, HorarioRecord> FK_FILMEHORARIO_HORARIO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_HORARIO_PRIMARY, FuncionarioHorario.FUNCIONARIO_HORARIO, "fk_filmehorario_horario_id", FuncionarioHorario.FUNCIONARIO_HORARIO.HORARIO_ID);
        public static final ForeignKey<IngressoRecord, SessaoRecord> FK_INGRESSO_SESSAO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_SESSAO_PRIMARY, Ingresso.INGRESSO, "fk_ingresso_sessao_id", Ingresso.INGRESSO.SESSAO_ID);
        public static final ForeignKey<IngressoRecord, TipoIngressoRecord> FK_INGRESSO_TIPOINGRESSO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_TIPO_INGRESSO_PRIMARY, Ingresso.INGRESSO, "fk_ingresso_tipoingresso_id", Ingresso.INGRESSO.TIPO_INGRESSO);
        public static final ForeignKey<SalaRecord, LocalizacaoRecord> FK_SALA_LOCALIZACAO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_LOCALIZACAO_PRIMARY, Sala.SALA, "fk_sala_localizacao_id", Sala.SALA.LOCALIZACAO_ID);
        public static final ForeignKey<SessaoRecord, FilmeRecord> FK_SESSAO_FILME_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_FILME_PRIMARY, Sessao.SESSAO, "fk_sessao_filme_id", Sessao.SESSAO.FILME_ID);
        public static final ForeignKey<SessaoRecord, SalaRecord> FK_SESSAO_SALA_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_SALA_PRIMARY, Sessao.SESSAO, "fk_sessao_sala_id", Sessao.SESSAO.SALA_ID);
        public static final ForeignKey<SessaoRecord, HorarioRecord> FK_SESSAO_HORARIO_ID = Internal.createForeignKey(br.edu.uni7.sicamovie.persistence.Keys.KEY_HORARIO_PRIMARY, Sessao.SESSAO, "fk_sessao_horario_id", Sessao.SESSAO.HORARIO_ID);
    }
}
