USE bd_sica_movie;

INSERT INTO `horario`(`descricao`) VALUES ("16:00");
INSERT INTO `horario`(`descricao`) VALUES ("17:00");
INSERT INTO `horario`(`descricao`) VALUES ("18:00");
INSERT INTO `horario`(`descricao`) VALUES ("19:30");
INSERT INTO `horario`(`descricao`) VALUES ("20:00");
INSERT INTO `horario`(`descricao`) VALUES ("22:00");
INSERT INTO `horario`(`descricao`) VALUES ("24:00");

INSERT INTO `localizacao`(`descricao`) VALUES ("North Shopping Siqueira");
INSERT INTO `localizacao`(`descricao`) VALUES ("South Shopping Siqueira");
INSERT INTO `localizacao`(`descricao`) VALUES ("Centro Cultural Siqueira do Mar");
INSERT INTO `localizacao`(`descricao`) VALUES ("Shopping Via Siqueira");

INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia de Iracema", 300, 1);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Majorlândia", 400, 1);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Cumbuco", 300, 1);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Jericoacoara", 300, 1);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Canoa Quebrada", 300, 1);

INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Ponta Negra", 300, 2);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Areia Preta", 400, 2);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia dos Artistas", 300, 2);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia do Forte", 300, 2);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia de Pipa", 300, 2);

INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Boa Viagem", 300, 3);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia do Pina", 400, 3);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Buraco da Véia", 300, 3);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Port de Galinhas", 300, 3);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia de Piedade", 300, 3);

INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Prainha", 300, 4);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Praia de Itacarezinho", 400, 4);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Taipus de Fora", 300, 4);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Morere", 300, 4);
INSERT INTO `sala`(`nome`, `capacidade`, `localizacao_id`) VALUES ("Taperapuan", 300, 4);

INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Palma de Ouro", "É o prêmio de maior prestígio do Festival de Cinema de Cannes", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor qualidade artística de produção", "Oscar de melhor qualidade artística de produção", "2018");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor ator", "Oscar de melhor ator", "2013");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor atriz", "Oscar de melhor atriz", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor coreografia", "Oscar de melhor coreografia", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor filme", "Oscar de melhor filme", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar de melhor fotografia", "Oscar de melhor fotografia", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar Honorário", "Oscar Honorário", "2014");
INSERT INTO `premio`(`nome`, `descricao`, `ano_premiacao`) VALUES ("Oscar científico ou técnico", "Oscar científico ou técnico", "2014");

INSERT INTO `funcao`(`descricao`) VALUES ("Caixa");
INSERT INTO `funcao`(`descricao`) VALUES ("Lanterninha");
INSERT INTO `funcao`(`descricao`) VALUES ("Zelador");
INSERT INTO `funcao`(`descricao`) VALUES ("Supervisor Regional");
INSERT INTO `funcao`(`descricao`) VALUES ("Analista de Marketing");
INSERT INTO `funcao`(`descricao`) VALUES ("Gerente de Operações");
INSERT INTO `funcao`(`descricao`) VALUES ("Técnico de Áudio");
INSERT INTO `funcao`(`descricao`) VALUES ("Auxiliar de Manutenção");

INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("171747", "José dos Santos", "2017-11-21", 1000.00, 1, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("171748", "Maria Joelma do Nascimento", "2017-10-17", 1500.00, 2, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("171749", "Jonanthas Fabricio Ferreira", "2018-09-16", 998.00, 3, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181847", "Maicon Vasconcelos de Oliveira", "2019-03-09", 9000.00, 4, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181848", "Marina da Silva Santos", "2015-07-15", 1000.00, 5, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181849", "Jonas da Paz Gomes", "2014-06-14", 1712.00, 6, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("191947", "Henrique Jorge Albuquerque", "2013-06-01", 2698.00, 7, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("191948", "Jorge Siqueira Júnior", "2011-06-30", 1449.00, 8, 1);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("191949", "Mario Santos Silva", "2010-11-19", 1050.00, 2, 1);

INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("141547", "José da Silva", "2017-11-21", 1000.00, 1, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("141548", "Maria Joana do Nascimento", "2017-10-17", 1500.00, 2, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("141549", "Richard Fabricio Ferreira", "2018-09-16", 998.00, 3, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161947", "Fernando Vasconcelos de Oliveira", "2019-03-09", 9000.00, 4, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161948", "Mariana da Silva Santos", "2015-07-15", 1000.00, 5, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161949", "Joséfa da Paz Gomes", "2014-06-14", 1712.00, 6, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("091247", "Jorge Henrique Albuquerque", "2013-06-01", 2698.00, 7, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("091248", "Jonas Siqueira Júnior", "2011-06-30", 1449.00, 8, 2);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("091249", "Maicon Santos Silva", "2010-11-19", 1050.00, 2, 2);

INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131947", "José da Silva Sauron", "2017-11-21", 1000.00, 1, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131948", "José Maria do Nascimento", "2017-10-17", 1500.00, 2, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131949", "Richarlison Fabricio Ferreira", "2018-09-16", 998.00, 3, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161047", "Neymar Vasconcelos de Oliveira", "2019-03-09", 9000.00, 4, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161048", "Fabiano da Silva Santos", "2015-07-15", 1000.00, 5, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161049", "Marta da Paz Gomes", "2014-06-14", 1712.00, 6, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161847", "Victoria Henrique Albuquerque", "2013-06-01", 2698.00, 7, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161848", "Fernanda Siqueira Júnior", "2011-06-30", 1449.00, 8, 3);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("161849", "Nicole Santos Silva", "2010-11-19", 1050.00, 2, 3);

INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131047", "Jonas Esticado da Silva", "2017-11-21", 1000.00, 1, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131048", "Lucas Silveira do Nascimento", "2017-10-17", 1500.00, 2, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("131049", "Paulo Fabricio Ferreira", "2018-09-16", 998.00, 3, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181447", "Mario Vasconcelos de Oliveira", "2019-03-09", 9000.00, 4, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181448", "Moana da Silva Santos", "2015-07-15", 1000.00, 5, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("181449", "Ana da Paz Gomes", "2014-06-14", 1712.00, 6, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("010247", "Edson Henrique Albuquerque", "2013-06-01", 2698.00, 7, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("010248", "Jário Siqueira Júnior", "2011-06-30", 1449.00, 8, 4);
INSERT INTO `funcionario`(`matricula`, `nome`, `data_admissao`, `salario`, `funcao_id`, `localizacao_id`) VALUES ("010249", "Natalia Santos Silva", "2010-11-19", 1050.00, 2, 4);

INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (1, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (1, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (1, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (1, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (2, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (2, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (2, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (2, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (3, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (3, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (3, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (3, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (4, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (4, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (4, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (5, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (5, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (5, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (6, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (6, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (6, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (6, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (7, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (7, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (7, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (7, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (8, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (8, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (8, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (9, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (9, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (9, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (9, 4);

INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (10, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (10, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (10, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (10, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (11, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (11, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (11, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (11, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (12, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (12, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (12, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (12, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (13, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (13, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (13, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (14, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (14, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (14, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (15, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (15, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (15, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (15, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (16, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (16, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (16, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (16, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (17, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (17, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (17, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (18, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (18, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (18, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (18, 4);

INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (19, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (19, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (19, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (19, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (20, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (20, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (20, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (20, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (21, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (21, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (21, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (21, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (22, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (22, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (22, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (22, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (23, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (23, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (23, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (24, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (24, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (24, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (25, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (25, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (25, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (25, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (26, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (26, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (26, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (26, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (27, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (27, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (27, 5);

INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (28, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (28, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (28, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (28, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (29, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (29, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (29, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (29, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (30, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (30, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (30, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (30, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (31, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (31, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (31, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (31, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (32, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (32, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (32, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (32, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (33, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (33, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (33, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (34, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (34, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (34, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (35, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (35, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (35, 4);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (35, 5);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (36, 1);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (36, 2);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (36, 3);
INSERT INTO `funcionario_horario`(`funcionario_id`, `horario_id`) VALUES (36, 4);
